server:
  port: 7300

spring:
  datasource:
    url: jdbc:mysql://www.it307.top:3306/security-oauth2?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: mallmysql
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.central.generator.model
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志